[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM", "PYI"]
ignore = [
  "E402",  # import non in testa
  "E501",  # righe > 100 caratteri
  "E701",  # più istruzioni su una riga
  "E741",  # nome variabile ambiguo
  "SIM102",# if annidati (semplificazione)
  "B008",  # chiamate nei default arg
  "B904",  # raise from ...
  "UP022", # capture_output (miglioria futura)
]
